[package]
name = "kas"
version = "0.4.1"
authors = ["Diggory Hardy <git@dhardy.name>"]
edition = "2018"
license = "Apache-2.0"
description = "KAS GUI Toolkit"
readme = "README.md"
documentation = "https://docs.rs/kas/"
keywords = ["gui"]
categories = ["gui"]
repository = "https://github.com/kas-gui/kas"
exclude = ["/screenshots"]

[features]
# Enables usage of unstable Rust features
nightly = []

# Enables documentation of APIs for toolkits and internal use.
# This API is not intended for use by end-user applications and
# thus is omitted from built documentation by default.
# This flag does not change the API, only built documentation.
internal_doc = []

# Enables text shaping via HarfBuzz
# Shaping is part of Complex Text Layout, used for ligatures and where form
# depends on position and context (especially important for Arabic).
shaping = ["kas-text/shaping"]

[dependencies]
log = "0.4"
smallvec = "1.4"
stack_dst = { version = "0.6", optional = true }
bitflags = "1" # only used without winit
unicode-segmentation = "1.6"

[dependencies.kas-macros]
version = "0.4.0"
path = "kas-macros"

[dependencies.kas-text]
version = "0.1"
git = "https://github.com/kas-gui/kas-text"
rev = "549d4ed7d4a358b4993c4c4bd69cafa6f378207e"

[dependencies.winit]
# Provides translations for several winit types
version = "0.22"
optional = true

[workspace]
members = ["kas-macros", "kas-theme", "kas-wgpu"]

[package.metadata.docs.rs]
features = ["nightly", "stack_dst", "winit"]
