[package]
name = "kas-mandlebrot"
version = "0.9.1"
authors = ["Diggory Hardy <git@dhardy.name>"]
edition = "2018"
license = "Apache-2.0"
description = "KAS GUI / Mandlebrot example"
publish = false

[dependencies]
kas = { version = "0.9.1", path = "../.." }
chrono = "0.4"
env_logger = "0.8"
log = "0.4"
wgpu = { path = "/home/dhardy/projects/graphics/wgpu/wgpu", features = ["spirv"] }
bytemuck = "1.7.0"

[[bin]]
name = "mandlebrot"
path = "mandlebrot.rs"

[build-dependencies]
glob = "0.3"
