name: Build releases
on:
  push:
    branches:
      - master

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install dependencies
        run: sudo apt-get install -y libxkbcommon-dev libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Build examples
        run: |
          cargo build --manifest-path kas-wgpu/Cargo.toml --release --example calculator --example gallery --example mandlebrot
          strip target/release/calculator target/release/gallery target/release/mandlebrot
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: examples-ubuntu
          path: |
            target/release/calculator
            target/release/gallery
            target/release/mandlebrot

  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build examples
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.7
        run: |
          cargo build --manifest-path kas-wgpu/Cargo.toml --release --example calculator --example gallery --example mandlebrot
          strip target/release/calculator target/release/gallery target/release/mandlebrot
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: examples-macOS
          path: |
            target/release/calculator
            target/release/gallery
            target/release/mandlebrot

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build examples
        run: cargo build --manifest-path kas-wgpu/Cargo.toml --release --example calculator --example gallery --example mandlebrot
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: examples-windows
          path: |
            target/release/calculator.exe
            target/release/gallery.exe
            target/release/mandlebrot.exe
